name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-msrv:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check MSRV
        run: cargo check --workspace --all-targets --all-features
        env:
          RUSTUP_TOOLCHAIN: 1.91.0
